### ISSUE TITLE
Morning session P2P 30th March

### ISSUE THREAD

**Issue by rammazzoti2000** [rammazzoti2000/Ruby-capstone-project#3]
Morning session P2P 30th March

**Comment by nyatindopatrick** [comment]
Good work!

**Comment by adamclasic** [comment]
Very good work. No issues.

**Comment by dili021** [comment]
Why didn't you make `--fix`? :rofl: 
Great work!

**Comment by Kyle-Law** [comment]
Looks good to me. Great job @rammazzoti2000 ! 💯

**Comment by patriciachrysy** [comment]
Good job @rammazzoti2000, the project is clean. I'll just have a few remarks:
- You linter asks me to put a space after the comma or closing parenthesis which ends a line and you agree with me that it's useless if there is nothing after them
- The program breaks when there is no file passed in parameter to the function, Maybe you should manage the case when there is no file in order to check local files or just to throw a message and say there is no file
Again good job on this one, clean and simple
